### ISSUE TITLE
Dynamic realm base is broken in newer grape version

### ISSUE THREAD

**Issue by stefan-kolb** [stefan-kolb/nucleus#74]
routing_args may be nil
needs to be investigated before upgrading grape.

**Comment by stefan-kolb** [comment]
```
undefined method `key?' for nil:NilClass, [\"C:/Users/Stefan/Desktop/Github/nucleus/lib/nucleus_api/ext/grape/dynamic_realm_base.rb:40:in `block in update_realm_name'\", 
\"C:/Users/Stefan/Desktop/Github/nucleus/lib/nucleus_api/ext/grape/dynamic_realm_base.rb:40:in `collect'\", 
\"C:/Users/Stefan/Desktop/Github/nucleus/lib/nucleus_api/ext/grape/dynamic_realm_base.rb:40:in 
`update_realm_name'\", \"C:/Users/Stefan/Desktop/Github/nucleus/lib/nucleus_api/ext/grape/dynamic_realm_base.rb:13:in `_call'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/grape-0.16.2/lib/grape/middleware/auth/base.rb:19:in `call'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/grape-0.16.2/lib/grape/middleware/error.rb:29:in `block in call!'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/grape-0.16.2/lib/grape/middleware/error.rb:28:in `catch'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/grape-0.16.2/lib/grape/middleware/error.rb:28:in `call!'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/grape-0.16.2/lib/grape/middleware/base.rb:23:in `call'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/head.rb:12:in `call'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/grape-0.16.2/lib/grape/endpoint.rb:203:in `call!'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/grape-0.16.2/lib/grape/endpoint.rb:197:in `call'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/grape-0.16.2/lib/grape/router/route.rb:68:in `exec'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/grape-0.16.2/lib/grape/router.rb:63:in `block in identity'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/grape-0.16.2/lib/grape/router.rb:84:in `transaction'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/grape-0.16.2/lib/grape/router.rb:59:in `identity'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/grape-0.16.2/lib/grape/router.rb:44:in `block in call'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/grape-0.16.2/lib/grape/router.rb:107:in `with_optimization'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/grape-0.16.2/lib/grape/router.rb:43:in `call'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/grape-0.16.2/lib/grape/api.rb:112:in `call'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/urlmap.rb:68:in `block in call'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/urlmap.rb:53:in `each'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/urlmap.rb:53:in `call'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/static.rb:149:in `call'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/static.rb:149:in `call'\", 
\"C:/Users/Stefan/Desktop/Github/nucleus/lib/nucleus_api/rack_middleware/error_request_logger.rb:24:in `call'\", 
\"C:/Users/Stefan/Desktop/Github/nucleus/lib/nucleus_api/rack_middleware/access_logger.rb:21:in `call'\", 
\"C:/Users/Stefan/Desktop/Github/nucleus/lib/nucleus_api/rack_middleware/request_id.rb:22:in `call'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/request_store-1.3.1/lib/request_store/middleware.rb:9:in `call'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rack-ssl-enforcer-0.2.9/lib/rack/ssl-enforcer.rb:57:in `call'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:153:in `call'\", 
\"C:/Users/Stefan/Desktop/Github/nucleus/spec/adapter/helpers/rack_test_mock_session_patch.rb:6:in `request'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/bundler/gems/rack-test-2d3f78eed50a/lib/rack/test.rb:244:in `process_request'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/bundler/gems/rack-test-2d3f78eed50a/lib/rack/test.rb:58:in `get'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/airborne-0.2.5/lib/airborne/rack_test_requester.rb:11:in `make_request'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/airborne-0.2.5/lib/airborne/base.rb:33:in `get'\", 
\"C:/Users/Stefan/Desktop/Github/nucleus/spec/adapter/support/features/shared_example_adapter_regions.rb:15:in `block (3 levels) in <top (required)>'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/example.rb:441:in `instance_exec'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/example.rb:441:in `instance_exec'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/hooks.rb:350:in `run'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/hooks.rb:514:in `block in run_owned_hooks_for'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/hooks.rb:513:in `each'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/hooks.rb:513:in `run_owned_hooks_for'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/hooks.rb:600:in `block in run_example_hooks_for'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/hooks.rb:599:in `reverse_each'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/hooks.rb:599:in `run_example_hooks_for'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/hooks.rb:469:in `run'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/example.rb:488:in `run_before_example'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/example.rb:251:in `block in run'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/example.rb:494:in `block in with_around_and_singleton_context_hooks'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/example.rb:451:in `block in with_around_example_hooks'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/hooks.rb:471:in `block in run'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/hooks.rb:611:in `block in run_around_example_hooks_for'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/example.rb:336:in `call'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/example.rb:441:in `instance_exec'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/example.rb:441:in `instance_exec'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/hooks.rb:382:in `execute_with'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/hooks.rb:613:in `block (2 levels) in run_around_example_hooks_for'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/example.rb:336:in `call'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/hooks.rb:614:in `run_around_example_hooks_for'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/hooks.rb:471:in `run'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/example.rb:451:in `with_around_example_hooks'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/example.rb:494:in `with_around_and_singleton_context_hooks'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/example.rb:249:in `run'\", 
\"C:/Users/Stefan/Desktop/Github/nucleus/spec/adapter/helpers/rspec_eventmachine_patch.rb:28:in `run'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/example_group.rb:627:in `block in run_examples'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/example_group.rb:623:in `map'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/example_group.rb:623:in `run_examples'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/example_group.rb:589:in `run'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/example_group.rb:590:in `block in run'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/example_group.rb:590:in `map'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/example_group.rb:590:in `run'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/example_group.rb:590:in `block in run'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/example_group.rb:590:in `map'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/example_group.rb:590:in `run'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/example_group.rb:590:in `block in run'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/example_group.rb:590:in `map'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/example_group.rb:590:in `run'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:113:in `block (3 levels) in run_specs'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:113:in `map'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:113:in `block (2 levels) in run_specs'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1836:in `with_suite_hooks'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:112:in `block in run_specs'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/reporter.rb:77:in `report'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:111:in `run_specs'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:87:in `run'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:71:in `run'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:45:in `invoke'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/exe/rspec:4:in `<top (required)>'\", 
\"C:/Ruby23/bin/rspec:23:in `load'\", \"C:/Ruby23/bin/rspec:23:in `<top (required)>'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/ruby-debug-ide-0.6.1.beta2/lib/ruby-debug-ide.rb:88:in `debug_load'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/ruby-debug-ide-0.6.1.beta2/lib/ruby-debug-ide.rb:88:in `debug_program'\", 
\"C:/Ruby23/lib/ruby/gems/2.3.0/gems/ruby-debug-ide-0.6.1.beta2/bin/rdebug-ide:130:in `<top (required)>'\", 
\"-e:1:in `load'\", 
\"-e:1:in `<main>'\"]","error_code":500000,"more_info":"linktodoc"}"
```

**Comment by stefan-kolb** [comment]
Router was changed therefore env variables changed from `rack.routing_args` to `grape.routing_args`
