### ISSUE TITLE
Inline rack-stream functionality

### ISSUE THREAD

**Issue by stefan-kolb** [stefan-kolb/nucleus#81]

**Comment by stefan-kolb** [comment]
rack-stream is also broken for grape >= 0.14 

```
NoMethodError: undefined method `_rack_stream_proc' for #<Class:0x3e77cf8>
./lib/nucleus_api/rack_middleware/error_request_logger.rb:24:in `call'
./lib/nucleus_api/rack_middleware/access_logger.rb:21:in `call'
./lib/nucleus_api/rack_middleware/request_id.rb:22:in `call'
./spec/adapter/helpers/rack_test_mock_session_patch.rb:6:in `request'
./spec/adapter/support/features/shared_example_adapter_application_logs.rb:384:in `block (5 levels) in <top (required)>'
./spec/adapter/helpers/rspec_eventmachine_patch.rb:15:in `block (2 levels) in run'
```
